In [72]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [73]:
## Import Iris (flower) dataset etc.
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB ## Remember that these are the 3 classes

In [74]:
## Load the data:
data_iris = datasets.load_iris()
target = data_iris.target
data = data_iris.data

In [75]:
bayes = [GaussianNB, MultinomialNB, BernoulliNB]

In [76]:
## Function for classifying into each of the three classes and prediction:
def classify_predict(data, target):
    for b in bayes:
        if b == BernoulliNB:
            cls = b(binarize=data.mean(0))
        else:
            cls = b()
        ## Prediction:
        cls.fit(data, target)
        cfs = confusion_matrix(target, cls.predict(data))
        print(b.__name__)
        print(cfs)
        print()

In [77]:
print('Iris dataset')
classify_predict(data, target)

Iris dataset
GaussianNB
[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]

MultinomialNB
[[50  0  0]
 [ 0 46  4]
 [ 0  3 47]]

BernoulliNB
[[50  0  0]
 [ 6 19 25]
 [ 0  6 44]]



In [78]:
## Load the data (wine):
data_wine = datasets.load_wine()
target = data_wine.target
data = data_wine.data
type(target)

numpy.ndarray

In [79]:
print('Wine dataset')
classify_predict(data, target)

Wine dataset
GaussianNB
[[58  1  0]
 [ 0 70  1]
 [ 0  0 48]]

MultinomialNB
[[52  5  2]
 [ 3 61  7]
 [ 1  5 42]]

BernoulliNB
[[58  1  0]
 [ 4 62  5]
 [ 0  1 47]]



In [80]:
## Load the data (diabetes)
data_bCancer = datasets.load_breast_cancer()
target = data_bCancer.target
data = data_bCancer.data

In [81]:
print('Breast Cancer')
classify_predict(data, target)
#print(data_bCancer.DESCR)

Breast Cancer
GaussianNB
[[189  23]
 [ 10 347]]

MultinomialNB
[[163  49]
 [ 10 347]]

BernoulliNB
[[197  15]
 [ 21 336]]



In [82]:
print(dir(datasets))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_svmlight_format', 'base', 'california_housing', 'clear_data_home', 'covtype', 'dump_svmlight_file', 'fetch_20newsgroups', 'fetch_20newsgroups_vectorized', 'fetch_california_housing', 'fetch_covtype', 'fetch_kddcup99', 'fetch_lfw_pairs', 'fetch_lfw_people', 'fetch_mldata', 'fetch_olivetti_faces', 'fetch_rcv1', 'fetch_species_distributions', 'get_data_home', 'kddcup99', 'lfw', 'load_boston', 'load_breast_cancer', 'load_diabetes', 'load_digits', 'load_files', 'load_iris', 'load_linnerud', 'load_mlcomp', 'load_sample_image', 'load_sample_images', 'load_svmlight_file', 'load_svmlight_files', 'load_wine', 'make_biclusters', 'make_blobs', 'make_checkerboard', 'make_circles', 'make_classification', 'make_friedman1', 'make_friedman2', 'make_friedman3', 'make_gaussian_quantiles', 'make_hastie_10_2', 'make_low_rank_matrix', 'make_moons', 'make_multilabel_classificati

In [85]:
## Print classification and prediction for various datasets:
for x in dir(datasets):
    if x in ['load_wine', 'load_breast_cancer', 'load_digits', 'load_iris']:
        print(x)
        dataset = getattr(datasets, x)() ## Think about datasets.load_x()
        target = dataset.target
        data = dataset.data
        classify_predict(data, target)

load_breast_cancer
GaussianNB
[[189  23]
 [ 10 347]]

MultinomialNB
[[163  49]
 [ 10 347]]

BernoulliNB
[[197  15]
 [ 21 336]]

load_digits
GaussianNB
[[176   0   0   0   1   0   0   1   0   0]
 [  0 154   0   0   0   0   3   5  14   6]
 [  0  13 113   0   0   1   1   0  49   0]
 [  0   2   2 145   0   6   0   7  20   1]
 [  1   1   0   0 152   1   2  21   3   0]
 [  0   0   0   3   0 169   1   6   2   1]
 [  0   1   0   0   0   1 179   0   0   0]
 [  0   0   0   0   1   1   0 177   0   0]
 [  0   8   0   1   0   3   0  12 150   0]
 [  1   6   0   5   1   3   0  17  20 127]]

MultinomialNB
[[175   0   0   0   3   0   0   0   0   0]
 [  0 137  14   0   0   1   2   0  13  15]
 [  0   7 160   0   0   0   0   0   8   2]
 [  0   0   2 159   0   2   0   5   8   7]
 [  1   0   0   0 173   0   0   4   3   0]
 [  0   0   0   0   1 157   1   1   2  20]
 [  0   2   0   0   1   1 176   0   1   0]
 [  0   0   0   0   0   0   0 178   1   0]
 [  0  11   1   0   1   0   1   1 154   5]
 [  0   1   0   

In [88]:
plot(target), grid()

([<matplotlib.lines.Line2D at 0x109e89ac8>], None)