In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
from keras.datasets import mnist
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
bayes = [GaussianNB, MultinomialNB, BernoulliNB]

In [5]:
## Function for classifying into each of the three classes and prediction:
def classify_predict(data, target):
    for b in bayes:
        if b == BernoulliNB:
            cls = b(binarize=data.mean(0))
        else:
            cls = b()
        ## Prediction:
        cls.fit(data, target)
        cfs = confusion_matrix(target, cls.predict(data))
        score = cls.score(data, target)
        
        print('Bayes Model:', b.__name__)
        print(cfs)
        print('Score: ', round(score*100, 2), '%')
        print()

In [6]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [7]:
classify_predict(x_train, y_train)

Bayes Model: GaussianNB
[[5206    9   33   16    9   13  165    5  356  111]
 [   4 6341   15   33    3   12   74    4  173   83]
 [ 484  152 1786  474   33   37 1443   17 1444   88]
 [ 274  295   49 2277   11   15  268   46 2274  622]
 [ 114   39   49   33 1027   35  483   21 1259 2782]
 [ 525  122   33  125   34  336  273   11 3411  551]
 [  47   92   25    3    4   19 5572    0  148    8]
 [  27   36    9   54   51    8   15 1919  190 3956]
 [  88  722   23   51   19   33   80    6 3802 1027]
 [  30   31   17    7   33    4    4   83  112 5628]]
Score:  56.49 %

Bayes Model: MultinomialNB
[[5363    4   31   16   10   82  100    0  311    6]
 [   0 6311   45   40    6   28   33    3  259   17]
 [  79   82 4933  131   63    8  274   47  326   15]
 [  34  116  296 4955   12  123   59   47  290  199]
 [  19   20   37    5 4337   16  119   14  232 1043]
 [ 159   47   47  657  108 3584  131   12  473  203]
 [  62  115   83    3   30  134 5409    0   81    1]
 [  46  106   42   24  149    

In [8]:
#plt.figure(figsize=(10, 10))
#plt.hist(x_train)

In [9]:
classify_predict(x_test, y_test)

Bayes Model: GaussianNB
[[ 884    1    3    2    2    1   61    1    6   19]
 [   0 1101    2    2    1    2   13    0    9    5]
 [  56   47  323   91    9    7  342    6  133   18]
 [  39   81    8  484    5    5  144   11  110  123]
 [  18    5    5    1  227    5  142    9   76  494]
 [  75   38    4   31   11   82  124    2  412  113]
 [   6   16    5    0    1    4  921    0    4    1]
 [   2   18    0   10    9    0    7  346   23  613]
 [   7  143    5   12   10    5   84    5  413  290]
 [   5   11    4    8    5    0    4   10    6  956]]
Score:  57.37 %

Bayes Model: MultinomialNB
[[ 914    0    1    5    1    6   11    1   41    0]
 [   0 1067   20    9    0    0    5    0   33    1]
 [  16    8  872   17    9    2   37   14   56    1]
 [   4    8   45  849    1   16    4   14   45   24]
 [   4    2    6    0  707    0   23    1   39  200]
 [  22   11    7  106   21  601   16    5   74   29]
 [  10   17    9    0    8   29  866    0   19    0]
 [   1   21   15    4   25    